services:
  server:
      build: 
        context: .
      command: gunicorn -w 4 -b 0.0.0.0 manage:app
      volumes:
        - ./services/app/:/usr/src/app/
      ports:
        - 5001:5000
      env_file:
        - ./.env.prod
      depends_on:
        - db
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: