services:
  server:
      build: 
        context: .
      command: gunicorn -w 4 -b 0.0.0.0 project.app:app
      volumes:
        - ./app/:/usr/src/app/
      ports:
        - ./services/app/:/usr/src/app/
      env_file:
        - ./.env.prod
      depends_on:
        - db